single_qubit:
  0:
    GE:
      freq: 5463203378.043332
      T1: 9.1e-05
      T2*: 2.1e-05
      T2e: 6.6e-05
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.132678
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.804244
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.132678
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.792057
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5203594582.405483
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.012293
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.223661
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.012293
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.669324
            phase: 0.0
            ramp_fraction: 0.25
  1:
    GE:
      freq: 5323130083.034235
      T1: 8.5e-05
      T2*: 2.1e-05
      T2e: 3.9e-05
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0621
        - channel: Q1.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.266293
            anh: -260157670.03385544
            df: 0.0
            phase: 0.0
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0621
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.147542
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5061645913.00038
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.101104
        - channel: Q1.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.105
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.101104
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.57
            phase: 0.0
            ramp_fraction: 0.25
  2:
    GE:
      freq: 5185634436.191052
      T1: 8.3e-05
      T2*: 3.8e-05
      T2e: 2.0e-05
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.089794
        - channel: Q2.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.300936
            anh: -262979589.41769218
            df: 0.0
            phase: 0.0
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.089794
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.165679
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4922692346.77336
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.023501
        - channel: Q2.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.290962
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.023501
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.2
            phase: 0.0
            ramp_fraction: 0.25
  3:
    GE:
      freq: 5256430529.854673
      T1: 4.2e-05
      T2*: 1.0e-05
      T2e: 1.0e-05
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.01792
        - channel: Q3.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.333704
            anh: -259793266.41689777
            df: 0.0
            phase: 0.0
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.01792
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.185968
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4996615263.437776
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.136988
        - channel: Q3.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.326957
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.136988
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.22
            phase: 0.0
            ramp_fraction: 0.25
  4:
    GE:
      freq: 5460930297.316788
      T1: 5.0e-05
      T2*: 9.0e-06
      T2e: 7.0e-06
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.033962
        - channel: Q4.qdrv
          env: cosine_square
          length: 4.5e-08
          kwargs:
            amp: 0.901284
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.033962
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 9.0e-08
          kwargs:
            amp: 0.90188
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5202223160.268461
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.125474
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.29
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.125474
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.29
            phase: 0.0
            ramp_fraction: 0.25
  5:
    GE:
      freq: 5560259665.679482
      T1: 0.0001
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.04282
        - channel: Q5.qdrv
          env: cosine_square
          length: 4.5e-08
          kwargs:
            amp: 0.901284
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.04282
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 9.0e-08
          kwargs:
            amp: 0.904238
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5301913170.019956
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q5.qdrv
          env: cosine_square
          length: 4.5e-08
          kwargs:
            amp: 0.9
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 9.0e-08
          kwargs:
            amp: 0.9
            phase: 0.0
            ramp_fraction: 0.25
  6:
    GE:
      freq: 5868839061.62523
      T1: 4.7e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.017317
        - channel: Q6.qdrv
          env: cosine_square
          length: 6.5e-08
          kwargs:
            amp: 0.86425
            phase: 0.0
            ramp_fraction: 0.2
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.017317
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 9.0e-08
          kwargs:
            amp: 0.603029
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5616610426.85352
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q6.qdrv
          env: cosine_square
          length: 4.0e-08
          kwargs:
            amp: 0.654867
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 9.0e-08
          kwargs:
            amp: 0.29626
            phase: 0.0
            ramp_fraction: 0.25
  7:
    GE:
      freq: 5421685532.984831
      T1: 2.5e-05
      T2*: 1.5e-05
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.110308
        - channel: Q7.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.289853
            anh: -260926131.85729027
            df: 0.0
            phase: 0.0
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.110308
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.163586
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5160761401.127541
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.057176
        - channel: Q7.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.278079
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.057176
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.15
            phase: 0.0
            ramp_fraction: 0.25
two_qubit:
  (0, 1):
    CZ:
      freq: 5260000000.0
      pulse:
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.717624
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.724652
          phase: -2.039249
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 2.359178
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -1.343372
  (1, 2):
    CZ:
      freq: 5120000000.0
      pulse:
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.36013
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.36013
          phase: -2.371181
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -1.124193
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: -0.217869
  (2, 3):
    CZ:
      freq: 5100000000.0
      pulse:
      - channel: Q2.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.701967
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.699663
          phase: -0.322912
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: 0.26798
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 0.974254
  (3, 4):
    CZ:
      freq: 5330000000.0
      pulse:
      - channel: Q3.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
  (4, 5):
    CZ:
      freq: 5400000000.0
      pulse:
      - channel: Q4.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
  (5, 6):
    CZ:
      freq: 5500000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (6, 7):
    CZ:
      freq: 5520000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (7, 0):
    CZ:
      freq: 5370000000.0
      pulse:
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.5e-07
        kwargs:
          amp: 0.795632
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.706434
          phase: 0.692496
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: -0.539758
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 0.026155
readout:
  0:
    channel: 7
    amp: 0.037
    freq: 6554556854.218374
    phase: 2.2
  1:
    channel: 4
    amp: 0.03
    freq: 6558907827.371197
    phase: 3.2
  2:
    channel: 1
    amp: 0.037
    freq: 6658224601.204804
    phase: 1.2
  3:
    channel: 3
    amp: 0.028
    freq: 6699517073.864432
    phase: 3.2
  4:
    channel: 5
    amp: 0.022
    freq: 6709558215.418671
    phase: -1.5
  5:
    channel: 6
    amp: 0.022
    freq: 6707928573.902684
    phase: -1.0
  6:
    channel: 2
    amp: 0.04
    freq: 6783491290.240388
    phase: 0.9312892237695153
  7:
    channel: 0
    amp: 0.05
    freq: 6835987148.190145
    phase: 3.3
  esp:
    enable: false
    qubits:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  delay: 6.0e-07
  herald: true
  length: 4.0e-06
  reset: 1.0e-05
  sample_rate: 500000000.0
  env: cosine_square
  kwargs:
    phase: 0.0
    ramp_fraction: 0.25
reset:
  active:
    enable: false
    n_resets: 3
    feedback_delay: 2.0e-07
  passive:
    delay: 0.0005
hardware:
  ADC_sample_rate: null
  DAC_sample_rate: 8000000000.0
  readout_LO: null
  qubit_LO: null
