single_qubit:
  0:
    GE:
      freq: 5464582928.04333
      T1: 7.4e-05
      T2*: 1.7e-05
      T2e: 3.6e-05
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.15539
        - channel: Q0.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.32721
            anh: -259730345.6378498
            df: 0.0
            phase: 0.0
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.15539
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.17952
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5212898982.40548
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.056613
        - channel: Q0.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.15273
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.056613
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 5.0e-08
          kwargs:
            amp: 0.15214
            phase: 0.0
            ramp_fraction: 0.25
  1:
    GE:
      freq: 5323341823.03424
      T1: 0.000129
      T2*: 2.5e-05
      T2e: 3.9e-05
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.03342
        - channel: Q1.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.37705
            anh: -260157670.03385544
            df: 0.0
            phase: 0.0
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.03342
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.21001
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5063365013.00038
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.047498
        - channel: Q1.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.141
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.047498
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 5.0e-08
          kwargs:
            amp: 0.1413
            phase: 0.0
            ramp_fraction: 0.25
  2:
    GE:
      freq: 5185715656.19105
      T1: 0.000154
      T2*: 6.3e-05
      T2e: 7.7e-05
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.12841
        - channel: Q2.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.40077
            anh: -262979589.41769218
            df: 0.0
            phase: 0.0
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.12841
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.21989
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4922639646.77336
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.029776
        - channel: Q2.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.16534
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.029776
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 5.0e-08
          kwargs:
            amp: 0.16901
            phase: 0.0
            ramp_fraction: 0.25
  3:
    GE:
      freq: 5256361979.85467
      T1: 4.97e-05
      T2*: 3.9e-05
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.040201
        - channel: Q3.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.41984
            anh: -259793266.41689777
            df: 0.0
            phase: 0.0
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.040201
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.2323
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4996428263.43778
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.072132
        - channel: Q3.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.1834
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.072132
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 5.0e-08
          kwargs:
            amp: 0.18756
            phase: 0.0
            ramp_fraction: 0.25
  4:
    GE:
      freq: 5461992717.31679
      T1: 0.000134
      T2*: 4.0e-05
      T2e: 5.0e-05
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.1198
        - channel: Q4.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.42729
            anh: -258908157.04832935
            df: 0.0
            phase: 0.0
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.1198
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.23477
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5203202560.26846
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.077687
        - channel: Q4.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.15744
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.077687
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 5.0e-08
          kwargs:
            amp: 0.15821
            phase: 0.0
            ramp_fraction: 0.25
  5:
    GE:
      freq: 5560231465.67948
      T1: 8.2e-05
      T2*: 4.1e-05
      T2e: 4.7e-05
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.06012
        - channel: Q5.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.43054
            anh: -257940095.6595192
            df: 0.0
            phase: 0.0
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.06012
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.23963
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5302333350.01996
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.030417
        - channel: Q5.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.15127
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.030417
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 5.0e-08
          kwargs:
            amp: 0.15905
            phase: 0.0
            ramp_fraction: 0.25
  6:
    GE:
      freq: 5868871161.62523
      T1: 5.35e-05
      T2*: 3.9e-05
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.056122
        - channel: Q6.qdrv
          env: cosine_square
          length: 4.0e-08
          kwargs:
            amp: 0.80302
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.056122
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 7.5e-08
          kwargs:
            amp: 0.87712
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5616619726.85352
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.072726
        - channel: Q6.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.6094
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.072726
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 5.0e-08
          kwargs:
            amp: 0.63977
            phase: 0.0
            ramp_fraction: 0.25
  7:
    GE:
      freq: 5422193792.98483
      T1: 1.99e-05
      T2*: 5.9e-06
      T2e: 2.8e-05
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.12844
        - channel: Q7.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.35249
            anh: -260926131.85729027
            df: 0.0
            phase: 0.0
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.12844
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.19986
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5162144801.12754
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.26852
        - channel: Q7.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.12818
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.26852
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 5.0e-08
          kwargs:
            amp: 0.13956
            phase: 0.0
            ramp_fraction: 0.25
two_qubit:
  (0, 1):
    CZ:
      freq: 5385000000.0
      pulse:
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.59011
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.59011
          phase: 1.65499
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 0.97727
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: 1.26753
  (1, 2):
    CZ:
      freq: 5120000000.0
      pulse:
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.43159
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.54619
          phase: -2.09718
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: 2.03318
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: 0.66408
      dynamical_decoupling:
        enable: false
        method: XY
        n_pulses: 4
        qubits:
        - 0
  (2, 3):
    CZ:
      freq: 5160000000.0
      pulse:
      - channel: Q2.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.48691
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.48691
          phase: -0.25398
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: -0.59277
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 0.69689
      dynamical_decoupling:
        enable: false
        method: XY
        n_pulses: 4
        qubits:
        - 4
  (3, 4):
    CZ:
      freq: 5240000000.0
      pulse:
      - channel: Q3.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.3993
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.37899
          phase: -1.15184
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 2.79303
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: -1.24792
      dynamical_decoupling:
        enable: false
        method: XY
        n_pulses: 4
        qubits:
        - 5
  (4, 5):
    CZ:
      freq: 5400000000.0
      pulse:
      - channel: Q4.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.66634
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.66634
          phase: 0.04837
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: 1.02554
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 3.14
  (5, 6):
    CZ:
      freq: 5500000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (6, 7):
    CZ:
      freq: 5520000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (7, 0):
    CZ:
      freq: 5370000000.0
      pulse:
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.5e-07
        kwargs:
          amp: 0.795632
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.706434
          phase: 0.692496
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: -0.539758
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 0.026155
readout:
  0:
    channel: 7
    amp: 0.0545
    freq: 6555381854.21837
    length: 1.48e-06
    phase: 0.0
    delay: 4.25e-07
  1:
    channel: 4
    amp: 0.045
    freq: 6559002827.3712
    length: 1.5e-06
    phase: 0.8
    delay: 4.4e-07
  2:
    channel: 1
    amp: 0.065
    freq: 6659054601.2048
    length: 1.63e-06
    phase: 1.9
    delay: 2.0e-07
  3:
    channel: 3
    amp: 0.056
    freq: 6699548073.86443
    length: 1.53e-06
    phase: 1.2
    delay: 3.9e-07
  4:
    channel: 5
    amp: 0.0685
    freq: 6710633215.41867
    length: 1.45e-06
    phase: -0.1
    delay: 4.6e-07
  5:
    channel: 6
    amp: 0.05
    freq: 6708678573.90268
    length: 1.46e-06
    phase: 0.9
    delay: 4.6e-07
  6:
    channel: 2
    amp: 0.057
    freq: 6783991290.24039
    length: 1.4e-06
    phase: 0.0
    delay: 3.725e-07
  7:
    channel: 0
    amp: 0.07
    freq: 6836612148.19014
    length: 1.44e-06
    phase: 2.0
    delay: 4.6e-07
  esp:
    enable: false
    qubits:
    - 2
    - 3
    - 5
  herald: true
  reset: 1.0e-05
  sample_rate: 500000000.0
  env: sine
  kwargs:
    phase: 0.0
reset:
  active:
    enable: false
    n_resets: 3
    feedback_delay: 2.0e-07
  passive:
    delay: 0.0005
hardware:
  ADC_sample_rate: null
  DAC_sample_rate: 8000000000.0
  readout_LO: null
  qubit_LO: null
