single_qubit:
  0:
    GE:
      freq: 5463255378.043332
      T1: 0.0001
      T2*: 3.1e-05
      T2e: 6.6e-05
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.083403
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.341213
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.083403
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.793257
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5203634582.405483
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.046617
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.225802
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.046617
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.224321
            phase: 0.0
            ramp_fraction: 0.25
  1:
    GE:
      freq: 5323218323.034235
      T1: 0.000113
      T2*: 3.5e-05
      T2e: 4.3e-05
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.057961
        - channel: Q1.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.267053
            anh: -260157670.03385544
            df: 0.0
            phase: 0.0
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.057961
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.147264
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5063060713.00038
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.1
        - channel: Q1.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.113269
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.1
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.117663
            phase: 0.0
            ramp_fraction: 0.25
  2:
    GE:
      freq: 5185755436.191052
      T1: 0.00018
      T2*: 6.3e-05
      T2e: 8.1e-05
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.057699
        - channel: Q2.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.300064
            anh: -262979589.41769218
            df: 0.0
            phase: 0.0
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.057699
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.164651
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4922655346.77336
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.017523
        - channel: Q2.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.106366
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.017523
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.105686
            phase: 0.0
            ramp_fraction: 0.25
  3:
    GE:
      freq: 5256513629.854673
      T1: 4.9e-05
      T2*: 2.2e-05
      T2e: 3.7e-05
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.004142
        - channel: Q3.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.334091
            anh: -259793266.41689777
            df: 0.0
            phase: 0.0
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.004142
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.185394
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4996609263.437776
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.046146
        - channel: Q3.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.126889
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.046146
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.127038
            phase: 0.0
            ramp_fraction: 0.25
  4:
    GE:
      freq: 5461573897.316788
      T1: 7.7e-05
      T2*: 3.2e-05
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.015053
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.865472
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.015053
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 9.0e-08
          kwargs:
            amp: 0.573813
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5202726760.268461
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.154076
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.241267
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.154076
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.241959
            phase: 0.0
            ramp_fraction: 0.25
  5:
    GE:
      freq: 5560245665.679482
      T1: 8.7e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.013551
        - channel: Q5.qdrv
          env: cosine_square
          length: 4.0e-08
          kwargs:
            amp: 0.902294
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.013551
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 8.0e-08
          kwargs:
            amp: 0.901932
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5302354370.019956
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.034943
        - channel: Q5.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.350005
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.034943
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.35378
            phase: 0.0
            ramp_fraction: 0.25
  6:
    GE:
      freq: 5868852961.62523
      T1: 4.9e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.015994
        - channel: Q6.qdrv
          env: cosine_square
          length: 5.5e-08
          kwargs:
            amp: 0.900772
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.015994
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 1.1e-07
          kwargs:
            amp: 0.90315
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5616576426.85352
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.05129
        - channel: Q6.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.845287
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.05129
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.867725
            phase: 0.0
            ramp_fraction: 0.25
  7:
    GE:
      freq: 5421767032.984831
      T1: 2.4e-05
      T2*: 3.6e-05
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.068079
        - channel: Q7.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.296477
            anh: -260926131.85729027
            df: 0.0
            phase: 0.0
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.068079
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.162209
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5160753501.127541
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.040957
        - channel: Q7.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.108898
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.040957
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.108091
            phase: 0.0
            ramp_fraction: 0.25
two_qubit:
  (0, 1):
    CZ:
      freq: 5260000000.0
      pulse:
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.717624
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.724652
          phase: -2.039249
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 2.359178
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -1.343372
  (1, 2):
    CZ:
      freq: 5120000000.0
      pulse:
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.36013
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.36013
          phase: -2.371181
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -1.124193
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: -0.217869
  (2, 3):
    CZ:
      freq: 5100000000.0
      pulse:
      - channel: Q2.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.701967
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.699663
          phase: -0.322912
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: 0.26798
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 0.974254
  (3, 4):
    CZ:
      freq: 5330000000.0
      pulse:
      - channel: Q3.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
  (4, 5):
    CZ:
      freq: 5400000000.0
      pulse:
      - channel: Q4.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
  (5, 6):
    CZ:
      freq: 5500000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (6, 7):
    CZ:
      freq: 5520000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (7, 0):
    CZ:
      freq: 5370000000.0
      pulse:
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.5e-07
        kwargs:
          amp: 0.795632
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.706434
          phase: 0.692496
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: -0.539758
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 0.026155
readout:
  0:
    channel: 7
    amp: 0.037
    freq: 6555456854.218374
    phase: 0.0
  1:
    channel: 4
    amp: 0.03
    freq: 6559207827.371197
    phase: 1.9
  2:
    channel: 1
    amp: 0.039
    freq: 6658424601.204804
    phase: 0.9
  3:
    channel: 3
    amp: 0.032
    freq: 6699517073.864432
    phase: 3.5
  4:
    channel: 5
    amp: 0.043
    freq: 6709958215.418671
    phase: -0.3
  5:
    channel: 6
    amp: 0.031
    freq: 6707928573.902684
    phase: -0.5
  6:
    channel: 2
    amp: 0.038
    freq: 6783691290.240388
    phase: 1.3
  7:
    channel: 0
    amp: 0.047
    freq: 6836587148.190145
    phase: 2.0
  esp:
    enable: false
    qubits:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  delay: 6.0e-07
  herald: true
  length: 4.0e-06
  reset: 1.0e-05
  sample_rate: 500000000.0
  env: cosine_square
  kwargs:
    phase: 0.0
    ramp_fraction: 0.25
reset:
  active:
    enable: false
    n_resets: 3
    feedback_delay: 2.0e-07
  passive:
    delay: 0.0005
hardware:
  ADC_sample_rate: null
  DAC_sample_rate: 8000000000.0
  readout_LO: null
  qubit_LO: null
