single_qubit:
  0:
    GE:
      freq: 4462778789.062685
      T1: 0.00012
      T2*: 2.1e-05
      T2e: 6.6e-05
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.013636
        - channel: Q0.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.160729
            anh: -270000000.0
            df: 0.0
            phase: 0.0
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.013636
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.15
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.4
            phase: 0.0
            ramp_fraction: 0.25
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.4
            phase: 0.0
            ramp_fraction: 0.25
  1:
    GE:
      freq: 4673626401.204112
      T1: 0.00017
      T2*: 2.1e-05
      T2e: 3.9e-05
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.09047
        - channel: Q1.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.692612
            anh: -270000000.0
            df: 0.0
            phase: 0.0
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.09047
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.45
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4400700000.0
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.57
            phase: 0.0
            ramp_fraction: 0.25
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.57
            phase: 0.0
            ramp_fraction: 0.25
  2:
    GE:
      freq: 4944775765.306334
      T1: 0.00013
      T2*: 1.9e-05
      T2e: 1.9e-05
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.020023
        - channel: Q2.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.478588
            anh: -270000000.0
            df: 0.0
            phase: 0.0
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.020023
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.38
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4672600000.0
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.2
            phase: 0.0
            ramp_fraction: 0.25
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.2
            phase: 0.0
            ramp_fraction: 0.25
  3:
    GE:
      freq: 5110918752.907667
      T1: 0.00014
      T2*: 1.0e-05
      T2e: 1.0e-05
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.136988
        - channel: Q3.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.203512
            anh: -270000000.0
            df: 0.0
            phase: 0.0
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.136988
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.17
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4849300000.0
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.22
            phase: 0.0
            ramp_fraction: 0.25
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.22
            phase: 0.0
            ramp_fraction: 0.25
  4:
    GE:
      freq: 5349096970.067185
      T1: 5.0e-05
      T2*: 9.0e-06
      T2e: 7.0e-06
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.125474
        - channel: Q4.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.678069
            anh: -270000000.0
            df: 0.0
            phase: 0.0
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.125474
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.11
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5089500000.0
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.29
            phase: 0.0
            ramp_fraction: 0.25
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.29
            phase: 0.0
            ramp_fraction: 0.25
  5:
    GE:
      freq: 5901336962.572675
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q5.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.697208
            anh: -270000000.0
            df: 0.0
            phase: 0.0
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.13
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5263900000.0
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.2
            phase: 0.0
            ramp_fraction: 0.25
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.2
            phase: 0.0
            ramp_fraction: 0.25
  6:
    GE:
      freq: 5878566778.000434
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q6.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.467096
            anh: -270000000.0
            df: 0.0
            phase: 0.0
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.52
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5615900000.0
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.72
            phase: 0.0
            ramp_fraction: 0.25
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.72
            phase: 0.0
            ramp_fraction: 0.25
  7:
    GE:
      freq: 5619597772.789028
      T1: 1.4e-05
      T2*: 1.5e-05
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.057176
        - channel: Q7.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.456388
            anh: -270000000.0
            df: 0.0
            phase: 0.0
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.057176
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.4
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5356000000.0
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.15
            phase: 0.0
            ramp_fraction: 0.25
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.15
            phase: 0.0
            ramp_fraction: 0.25
two_qubit:
  (0, 1):
    CZ:
      freq: 4430000000.0
      pulse:
      - channel: Q0.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q1.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
  (1, 2):
    CZ:
      freq: 4630000000.0
      pulse:
      - channel: Q1.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q2.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
  (2, 3):
    CZ:
      freq: 4900000000.0
      pulse:
      - channel: Q2.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q3.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
  (3, 4):
    CZ:
      freq: 5030000000.0
      pulse:
      - channel: Q3.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q4.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
  (4, 5):
    CZ:
      freq: 5300000000.0
      pulse:
      - channel: Q4.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q5.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
  (5, 6):
    CZ:
      freq: 5500000000.0
      pulse:
      - channel: Q5.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q6.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
  (6, 7):
    CZ:
      freq: 5550000000.0
      pulse:
      - channel: Q6.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q7.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
  (7, 0):
    CZ:
      freq: 4900000000.0
      pulse:
      - channel: Q7.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q0.qdrv
        env: virtualz
        length: 0.0
        kwargs:
          phase: 0.0
readout:
  0:
    channel: 7
    amp: 0.021
    freq: 6554368952.374638
    phase: 1.0471975511965976
  1:
    channel: 4
    amp: 0.0183
    freq: 6558439922.632911
    phase: 3.400421796562137
  2:
    channel: 1
    amp: 0.01664
    freq: 6658008967.32158
    phase: -1.1667773522863918
  3:
    channel: 3
    amp: 0.0179
    freq: 6700134795.120309
    phase: 2.0
  4:
    channel: 6
    amp: 0.02
    freq: 6711440184.690463
    phase: 3.624878768638384
  5:
    channel: 6
    amp: 0.025
    freq: 6709360370.806432
    phase: 6.275011358862511
  6:
    channel: 2
    amp: 0.05
    freq: 6785153568.914835
    phase: 0.9312892237695153
  7:
    channel: 0
    amp: 0.04
    freq: 6835470849.262068
    phase: 4.256638268772688
  esp:
    enable: false
    qubits:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  delay: 6.0e-07
  herald: true
  length: 4.0e-06
  reset: 1.0e-05
  sample_rate: 500000000.0
  env: cosine_square
  kwargs:
    phase: 0.0
    ramp_fraction: 0.25
reset:
  active:
    enable: false
    n_resets: 10
    feedback_delay: 2.0e-07
  passive:
    delay: 0.0005
hardware:
  ADC_sample_rate: null
  DAC_sample_rate: 8000000000.0
  readout_LO: null
  qubit_LO: null
