single_qubit:
  0:
    GE:
      freq: 5463254928.043332
      T1: 0.00011
      T2*: 9.0e-06
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.203463
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.797488
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.203463
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.783907
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5203563582.405483
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.014591
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.225172
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.014591
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.2245
            phase: 0.0
            ramp_fraction: 0.25
  1:
    GE:
      freq: 5323201123.034235
      T1: 0.00013
      T2*: 2.6e-05
      T2e: 4.4e-05
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.062917
        - channel: Q1.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.265588
            anh: -260157670.03385544
            df: 0.0
            phase: 0.0
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.062917
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.147156
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5062228713.00038
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.025844
        - channel: Q1.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.113633
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.025844
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.093698
            phase: 0.0
            ramp_fraction: 0.25
  2:
    GE:
      freq: 5185705436.191052
      T1: 0.00014
      T2*: 5.0e-05
      T2e: 8.2e-05
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.100683
        - channel: Q2.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.295306
            anh: -262979589.41769218
            df: 0.0
            phase: 0.0
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.100683
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.162621
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4922652246.77336
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.027084
        - channel: Q2.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.106189
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.027084
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.105642
            phase: 0.0
            ramp_fraction: 0.25
  3:
    GE:
      freq: 5256476829.854673
      T1: 4.6e-05
      T2*: 2.0e-05
      T2e: 4.1e-05
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.001354
        - channel: Q3.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.331789
            anh: -259793266.41689777
            df: 0.0
            phase: 0.0
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.001354
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.184718
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4996572263.437776
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.065543
        - channel: Q3.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.127115
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.065543
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.126567
            phase: 0.0
            ramp_fraction: 0.25
  4:
    GE:
      freq: 5461563097.316788
      T1: 0.00013
      T2*: 3.7e-05
      T2e: 4.2e-05
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.02542
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.861002
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.02542
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 9.0e-08
          kwargs:
            amp: 0.576166
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5202666160.268461
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.001941
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.240845
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.001941
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.24281
            phase: 0.0
            ramp_fraction: 0.25
  5:
    GE:
      freq: 5560255165.679482
      T1: 9.2e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.03001
        - channel: Q5.qdrv
          env: cosine_square
          length: 4.0e-08
          kwargs:
            amp: 0.969217
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.03001
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 8.0e-08
          kwargs:
            amp: 0.952164
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5302297470.019956
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.047869
        - channel: Q5.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.345241
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.047869
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.335974
            phase: 0.0
            ramp_fraction: 0.25
  6:
    GE:
      freq: 5868832961.62523
      T1: 5.3e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.046762
        - channel: Q6.qdrv
          env: cosine_square
          length: 5.5e-08
          kwargs:
            amp: 0.84919
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.046762
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 1.1e-07
          kwargs:
            amp: 0.862559
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5616554426.85352
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.069903
        - channel: Q6.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.806577
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.069903
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.833249
            phase: 0.0
            ramp_fraction: 0.25
  7:
    GE:
      freq: 5421755532.984831
      T1: 2.3e-05
      T2*: 3.6e-05
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.013774
        - channel: Q7.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.286948
            anh: -260926131.85729027
            df: 0.0
            phase: 0.0
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.013774
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.158742
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5160699501.127541
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.035697
        - channel: Q7.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.111243
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.035697
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.110731
            phase: 0.0
            ramp_fraction: 0.25
two_qubit:
  (0, 1):
    CZ:
      freq: 5260000000.0
      pulse:
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.695237
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.627746
          phase: -1.345344
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 1.927649
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -0.627183
  (1, 2):
    CZ:
      freq: 5120000000.0
      pulse:
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.344631
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.395164
          phase: -2.296815
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: 3.027298
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: 2.605024
  (2, 3):
    CZ:
      freq: 5150000000.0
      pulse:
      - channel: Q2.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.878844
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.878844
          phase: -0.087428
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: 1.538004
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 1.105557
  (3, 4):
    CZ:
      freq: 5230000000.0
      pulse:
      - channel: Q3.qdrv
        env: cosine_square
        length: 2.5e-07
        kwargs:
          amp: 0.879833
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: cosine_square
        length: 2.5e-07
        kwargs:
          amp: 0.879833
          phase: -1.193421
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
  (4, 5):
    CZ:
      freq: 5400000000.0
      pulse:
      - channel: Q4.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.732658
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.732658
          phase: 0.298501
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: -0.441041
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.752092
  (5, 6):
    CZ:
      freq: 5500000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (6, 7):
    CZ:
      freq: 5520000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (7, 0):
    CZ:
      freq: 5370000000.0
      pulse:
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.5e-07
        kwargs:
          amp: 0.795632
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.706434
          phase: 0.692496
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: -0.539758
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 0.026155
readout:
  0:
    channel: 7
    amp: 0.05
    freq: 6555456854.218374
    phase: 0.0
    delay: 4.0e-07
  1:
    channel: 4
    amp: 0.04
    freq: 6559107827.371197
    phase: 1.9
    delay: 4.0e-07
  2:
    channel: 1
    amp: 0.05
    freq: 6658504601.204804
    phase: 0.9
    delay: 4.0e-07
  3:
    channel: 3
    amp: 0.05
    freq: 6699523073.864432
    phase: 3.5
    delay: 4.0e-07
  4:
    channel: 5
    amp: 0.06
    freq: 6710258215.418671
    phase: -0.3
    delay: 4.0e-07
  5:
    channel: 6
    amp: 0.06
    freq: 6707928573.902684
    phase: -0.5
    delay: 4.0e-07
  6:
    channel: 2
    amp: 0.075
    freq: 6784291290.240388
    phase: 1.3
    delay: 4.0e-07
  7:
    channel: 0
    amp: 0.08
    freq: 6836587148.190145
    phase: 2.0
    delay: 4.0e-07
  esp:
    enable: true
    qubits:
    - 0
    - 2
    - 3
    - 5
    - 6
  herald: true
  length: 7.5e-07
  reset: 1.0e-05
  sample_rate: 500000000.0
  env: sine
  kwargs:
    phase: 0.0
reset:
  active:
    enable: false
    n_resets: 3
    feedback_delay: 2.0e-07
  passive:
    delay: 0.0005
hardware:
  ADC_sample_rate: null
  DAC_sample_rate: 8000000000.0
  readout_LO: null
  qubit_LO: null
