single_qubit:
  0:
    GE:
      freq: 5463253828.043332
      T1: 9.3e-05
      T2*: 3.9e-05
      T2e: 3.6e-05
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.05901
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.183025
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.05901
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.18206
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5203599582.405483
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.063936
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.126655
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.063936
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.1251
            phase: 0.0
            ramp_fraction: 0.25
  1:
    GE:
      freq: 5323197023.034235
      T1: 5.7e-05
      T2*: 1.4e-05
      T2e: 3.7e-05
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.132582
        - channel: Q1.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.391108
            anh: -260157670.03385544
            df: 0.0
            phase: 0.0
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.132582
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.21536
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5062167013.00038
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.041071
        - channel: Q1.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.141381
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.041071
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.11668
            phase: 0.0
            ramp_fraction: 0.25
  2:
    GE:
      freq: 5185748236.191052
      T1: 0.0001
      T2*: 4.6e-05
      T2e: 6.6e-05
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.100428
        - channel: Q2.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.407999
            anh: -262979589.41769218
            df: 0.0
            phase: 0.0
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.100428
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.22274
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4922684746.77336
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.020477
        - channel: Q2.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.138256
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.020477
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.13881
            phase: 0.0
            ramp_fraction: 0.25
  3:
    GE:
      freq: 5256393079.854673
      T1: 5.26e-05
      T2*: 2.6e-05
      T2e: 4.1e-05
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.000475
        - channel: Q3.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.430589
            anh: -259793266.41689777
            df: 0.0
            phase: 0.0
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.000475
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.23717
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4996357263.437776
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.05829
        - channel: Q3.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.155605
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.05829
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.15412
            phase: 0.0
            ramp_fraction: 0.25
  4:
    GE:
      freq: 5461561097.316788
      T1: 0.0001
      T2*: 2.6e-05
      T2e: 4.7e-05
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.010469
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.240373
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.010469
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.23974
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5202708560.268461
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.078046
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.131682
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.078046
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.13021
            phase: 0.0
            ramp_fraction: 0.25
  5:
    GE:
      freq: 5560235665.679482
      T1: 5.1e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.019124
        - channel: Q5.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.212029
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.019124
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.21227
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5302349570.01996
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.034594
        - channel: Q5.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.132091
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.034594
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.13101
            phase: 0.0
            ramp_fraction: 0.25
  6:
    GE:
      freq: 5868782961.62523
      T1: 6.0e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.028173
        - channel: Q6.qdrv
          env: cosine_square
          length: 6.5e-08
          kwargs:
            amp: 0.923108
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.028173
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 1.1e-07
          kwargs:
            amp: 0.90827
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5616572426.85352
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.156623
        - channel: Q6.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.253449
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.156623
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 7.0e-08
          kwargs:
            amp: 0.81583
            phase: 0.0
            ramp_fraction: 0.25
  7:
    GE:
      freq: 5421806792.98483
      T1: 8.5e-05
      T2*: 8.0e-05
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.063018
        - channel: Q7.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.35018
            anh: -260926131.85729027
            df: 0.0
            phase: 0.0
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.063018
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.20611
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5162175501.127541
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.005432
        - channel: Q7.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.134593
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.005432
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.13283
            phase: 0.0
            ramp_fraction: 0.25
two_qubit:
  (0, 1):
    CZ:
      freq: 5385000000.0
      pulse:
      - channel: Q0.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.47218
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.47218
          phase: 0.87346
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 0.41404
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -0.67194
  (1, 2):
    CZ:
      freq: 5120000000.0
      pulse:
      - channel: Q1.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.52244
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.52244
          phase: -2.11623
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -0.46824
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: -2.22455
      dynamical_decoupling:
        enable: false
        method: XY
        n_pulses: 4
        qubits:
        - 0
  (2, 3):
    CZ:
      freq: 5160000000.0
      pulse:
      - channel: Q2.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.61089
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.61089
          phase: -0.62786
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: 0.80879
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: -1.35574
      dynamical_decoupling:
        enable: false
        method: XY
        n_pulses: 4
        qubits:
        - 4
  (3, 4):
    CZ:
      freq: 5230000000.0
      pulse:
      - channel: Q3.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.685669
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.685669
          phase: -1.219475
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 2.021658
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: -1.01697
      dynamical_decoupling:
        enable: false
        method: XY
        n_pulses: 4
        qubits:
        - 5
  (4, 5):
    CZ:
      freq: 5400000000.0
      pulse:
      - channel: Q4.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.732658
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.732658
          phase: 0.298501
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: -0.441041
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.752092
  (5, 6):
    CZ:
      freq: 5500000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (6, 7):
    CZ:
      freq: 5520000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (7, 0):
    CZ:
      freq: 5370000000.0
      pulse:
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.5e-07
        kwargs:
          amp: 0.795632
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.706434
          phase: 0.692496
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: -0.539758
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 0.026155
readout:
  0:
    channel: 7
    amp: 0.0575
    freq: 6555781854.21837
    length: 9.8e-07
    phase: 0.0
    delay: 4.0e-07
  1:
    channel: 4
    amp: 0.055
    freq: 6558757827.3712
    length: 9.6e-07
    phase: 0.6
    delay: 4.75e-07
  2:
    channel: 1
    amp: 0.063
    freq: 6658429601.2048
    length: 9.1e-07
    phase: -2.3
    delay: 5.5e-07
  3:
    channel: 3
    amp: 0.061
    freq: 6699298073.86443
    length: 1.0e-06
    phase: 1.2
    delay: 4.25e-07
  4:
    channel: 5
    amp: 0.055
    freq: 6710483215.41867
    length: 1.04e-06
    phase: -0.3
    delay: 6.25e-07
  5:
    channel: 6
    amp: 0.0655
    freq: 6708453573.90268
    length: 9.4e-07
    phase: -0.5
    delay: 5.0e-07
  6:
    channel: 2
    amp: 0.06
    freq: 6783941290.24039
    length: 1.02e-06
    phase: 1.3
    delay: 3.75e-07
  7:
    channel: 0
    amp: 0.08225
    freq: 6836612148.19014
    length: 1.04e-06
    phase: 2.0
    delay: 4.75e-07
  esp:
    enable: false
    qubits:
    - 0
    - 3
    - 6
  herald: true
  reset: 1.0e-05
  sample_rate: 500000000.0
  env: sine
  kwargs:
    phase: 0.0
reset:
  active:
    enable: false
    n_resets: 3
    feedback_delay: 2.0e-07
  passive:
    delay: 0.0005
hardware:
  ADC_sample_rate: null
  DAC_sample_rate: 8000000000.0
  readout_LO: null
  qubit_LO: null
