single_qubit:
  0:
    GE:
      freq: 4461736318.073627
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q0.qdrv
            env: virtualz
            length: 0.0
            kwargs:
              phase: 0.0
          - channel: Q0.qdrv
            env: 'DRAG'
            length: 2.4e-8
            kwargs:
              alpha: 0.0 
              amp: 0.1
              anh: -270.e+6
              df: 0.0
              phase: 0.0
          - channel: Q0.qdrv
            env: virtualz
            length: 0.0
            kwargs:
              phase: 0.0
      X:
        pulse:
          - channel: Q0.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q0.qdrv
            env: 'cosine_square'
            length: 2.4e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
      X:
        pulse:
          - channel: Q0.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
  1:
    GE:
      freq: 4461736318.073627
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q1.qdrv
            env: 'DRAG'
            length: 2.4e-8
            kwargs:
              alpha: 0.0 
              amp: 0.1
              anh: -270.e+6
              df: 0.0
              phase: 0.0
      X:
        pulse:
          - channel: Q1.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q1.qdrv
            env: 'cosine_square'
            length: 2.4e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
      X:
        pulse:
          - channel: Q1.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
  2:
    GE:
      freq: 4461736318.073627
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q2.qdrv
            env: 'DRAG'
            length: 2.4e-8
            kwargs:
              alpha: 0.0 
              amp: 0.1
              anh: -270.e+6
              df: 0.0
              phase: 0.0
      X:
        pulse:
          - channel: Q2.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q2.qdrv
            env: 'cosine_square'
            length: 2.4e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
      X:
        pulse:
          - channel: Q2.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
  3:
    GE:
      freq: 4461736318.073627
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q3.qdrv
            env: 'DRAG'
            length: 2.4e-8
            kwargs:
              alpha: 0.0 
              amp: 0.1
              anh: -270.e+6
              df: 0.0
              phase: 0.0
      X:
        pulse:
          - channel: Q3.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q3.qdrv
            env: 'cosine_square'
            length: 2.4e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
      X:
        pulse:
          - channel: Q3.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
  4:
    GE:
      freq: 4461736318.073627
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q4.qdrv
            env: 'DRAG'
            length: 2.4e-8
            kwargs:
              alpha: 0.0 
              amp: 0.1
              anh: -270.e+6
              df: 0.0
              phase: 0.0
      X:
        pulse:
          - channel: Q4.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q4.qdrv
            env: 'cosine_square'
            length: 2.4e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
      X:
        pulse:
          - channel: Q4.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
  5:
    GE:
      freq: 4461736318.073627
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q5.qdrv
            env: 'DRAG'
            length: 2.4e-8
            kwargs:
              alpha: 0.0 
              amp: 0.1
              anh: -270.e+6
              df: 0.0
              phase: 0.0
      X:
        pulse:
          - channel: Q5.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q5.qdrv
            env: 'cosine_square'
            length: 2.4e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
      X:
        pulse:
          - channel: Q5.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
  6:
    GE:
      freq: 4461736318.073627
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q6.qdrv
            env: 'DRAG'
            length: 2.4e-8
            kwargs:
              alpha: 0.0 
              amp: 0.1
              anh: -270.e+6
              df: 0.0
              phase: 0.0
      X:
        pulse:
          - channel: Q6.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q6.qdrv
            env: 'cosine_square'
            length: 2.4e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
      X:
        pulse:
          - channel: Q6.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
  7:
    GE:
      freq: 4461736318.073627
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q7.qdrv
            env: 'DRAG'
            length: 2.4e-8
            kwargs:
              alpha: 0.0 
              amp: 0.1
              anh: -270.e+6
              df: 0.0
              phase: 0.0
      X:
        pulse:
          - channel: Q7.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
    EF:
      freq: 4181258902.85729
      T1:
      T2*:
      T2e:
      X90:
        pulse:
          - channel: Q7.qdrv
            env: 'cosine_square'
            length: 2.4e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
      X:
        pulse:
          - channel: Q7.qdrv
            env: 'cosine_square'
            length: 4.8e-8
            kwargs:
              amp: 0.1
              phase: 0.0
              ramp_fraction: 0.25
two_qubit:
  (0, 1):
    CZ:
      freq: -391492904
      pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q1.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
  (1, 2):
    CZ:
      freq: -391492904
      pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q2.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
  (2, 3):
    CZ:
      freq: -391492904
      pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q3.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
  (3, 4):
    CZ:
      freq: -391492904
      pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
  (4, 5):
    CZ:
      freq: -391492904
      pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
  (5, 6):
    CZ:
      freq: -391492904
      pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q6.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
  (6, 7):
    CZ:
      freq: -391492904
      pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q7.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
  (7, 0):
    CZ:
      freq: -391492904
      pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: cosine_square
          length: 2.0e-07
          kwargs:
            amp: 0.288
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.0
readout:
  0:
    channel: 7
    amp: 0.019724226371142798
    freq: 6554368952.374638
    phase: 0.0
  1:
    channel: 4
    amp: 0.01829905189877411
    freq: 6558439922.632911
    phase: 0.0
  2:
    channel: 1
    amp: 0.016645073053349783
    freq: 6658008967.32158
    phase: 0.0
  3:
    channel: 3
    amp: 0.017906057102356918
    freq: 6700134795.120309
    phase: 0.0
  4:
    channel: 5
    amp: 0.016127662739686993
    freq: 6711440184.690463
    phase: 0.0
  5:
    channel: 6
    amp: 0.0183
    freq: 6708160370.806432
    phase: 0.0
  6:
    channel: 2
    amp: 0.0305
    freq: 6785153568.914835
    phase: 0.0
  7:
    channel: 0
    amp: 0.93
    freq: 6835470849.262068
    phase: 0.0
  esp:
    enable: False
    qubits:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  delay: 6.e-07
  herald: True
  length: 1.0e-6
  reset: 1.e+5
  sample_rate: 8.e+9
  env: cosine_square
  kwargs:
    phase: 0.0
    ramp_fraction: 0.25
reset:
  active:
    enable: True
    n_resets: 1
    feedback_delay: 2.e-7
  passive:
    delay: 5.e-4 
hardware:
  ADC_sample_rate: 
  DAC_sample_rate: 8.e+9
  readout_LO:
  qubit_LO:
