single_qubit:
  0:
    GE:
      freq: 5463252928.043332
      T1: 0.00011
      T2*: 9.0e-06
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.079807
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.507379
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.079807
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.788013
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5203863582.405483
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.085815
        - channel: Q0.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.21913
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q0.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.085815
      X:
        pulse:
        - channel: Q0.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.219078
            phase: 0.0
            ramp_fraction: 0.25
  1:
    GE:
      freq: 5323209023.034235
      T1: 0.00013
      T2*: 2.6e-05
      T2e: 4.4e-05
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.027692
        - channel: Q1.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 1.0
            amp: 0.266054
            anh: -260157670.03385544
            df: 0.0
            phase: 0.0
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.027692
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.146858
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5062186513.00038
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.020028
        - channel: Q1.qdrv
          env: cosine_square
          length: 2.5e-08
          kwargs:
            amp: 0.112522
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q1.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.020028
      X:
        pulse:
        - channel: Q1.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.094029
            phase: 0.0
            ramp_fraction: 0.25
  2:
    GE:
      freq: 5185733436.191052
      T1: 0.00014
      T2*: 5.0e-05
      T2e: 8.2e-05
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.100178
        - channel: Q2.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.297567
            anh: -262979589.41769218
            df: 0.0
            phase: 0.0
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.100178
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.163958
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4922682246.77336
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.028697
        - channel: Q2.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.104537
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q2.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.028697
      X:
        pulse:
        - channel: Q2.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.104747
            phase: 0.0
            ramp_fraction: 0.25
  3:
    GE:
      freq: 5256476529.854673
      T1: 4.6e-05
      T2*: 2.0e-05
      T2e: 4.1e-05
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.015782
        - channel: Q3.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.331025
            anh: -259793266.41689777
            df: 0.0
            phase: 0.0
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.015782
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.184002
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 4996592263.437776
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.054188
        - channel: Q3.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.126644
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q3.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.054188
      X:
        pulse:
        - channel: Q3.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.125422
            phase: 0.0
            ramp_fraction: 0.25
  4:
    GE:
      freq: 5461571097.316788
      T1: 0.00013
      T2*: 3.7e-05
      T2e: 4.2e-05
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.082312
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.864298
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.082312
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 9.0e-08
          kwargs:
            amp: 0.57606
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5202713660.268461
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.051438
        - channel: Q4.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.246508
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q4.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.051438
      X:
        pulse:
        - channel: Q4.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.248854
            phase: 0.0
            ramp_fraction: 0.25
  5:
    GE:
      freq: 5560255665.679482
      T1: 9.2e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.020509
        - channel: Q5.qdrv
          env: cosine_square
          length: 4.0e-08
          kwargs:
            amp: 0.95726
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.020509
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 8.0e-08
          kwargs:
            amp: 0.953489
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5302352370.019956
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.09451
        - channel: Q5.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.350951
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q5.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.09451
      X:
        pulse:
        - channel: Q5.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.346192
            phase: 0.0
            ramp_fraction: 0.25
  6:
    GE:
      freq: 5868922961.62523
      T1: 5.3e-05
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.046762
        - channel: Q6.qdrv
          env: cosine_square
          length: 5.5e-08
          kwargs:
            amp: 0.859502
            phase: 0.0
            ramp_fraction: 0.15
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.046762
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 1.1e-07
          kwargs:
            amp: 0.938095
            phase: 0.0
            ramp_fraction: 0.15
    EF:
      freq: 5616603426.85352
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.156623
        - channel: Q6.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.325779
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q6.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: -0.156623
      X:
        pulse:
        - channel: Q6.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.609447
            phase: 0.0
            ramp_fraction: 0.25
  7:
    GE:
      freq: 5421750732.984831
      T1: 2.3e-05
      T2*: 3.6e-05
      T2e: 4.0e-05
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.062099
        - channel: Q7.qdrv
          env: DRAG
          length: 3.0e-08
          kwargs:
            alpha: 0.0
            amp: 0.284431
            anh: -260926131.85729027
            df: 0.0
            phase: 0.0
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.062099
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.156696
            phase: 0.0
            ramp_fraction: 0.25
    EF:
      freq: 5160740501.127541
      T1: null
      T2*: null
      T2e: null
      X90:
        pulse:
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.005013
        - channel: Q7.qdrv
          env: cosine_square
          length: 3.0e-08
          kwargs:
            amp: 0.106581
            phase: 0.0
            ramp_fraction: 0.25
        - channel: Q7.qdrv
          env: virtualz
          length: 0.0
          kwargs:
            phase: 0.005013
      X:
        pulse:
        - channel: Q7.qdrv
          env: cosine_square
          length: 6.0e-08
          kwargs:
            amp: 0.105325
            phase: 0.0
            ramp_fraction: 0.25
two_qubit:
  (0, 1):
    CZ:
      freq: 5260000000.0
      pulse:
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.695237
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.627746
          phase: -1.345344
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 1.927649
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -0.627183
  (1, 2):
    CZ:
      freq: 5120000000.0
      pulse:
      - channel: Q1.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.37698
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.457705
          phase: -2.296812
          ramp_fraction: 0.25
      - channel: Q1.qdrv
        env: virtualz
        freq: single_qubit/1/GE/freq
        length: 0.0
        kwargs:
          phase: -2.998583
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: -1.462109
  (2, 3):
    CZ:
      freq: 5150000000.0
      pulse:
      - channel: Q2.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.641247
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: cosine_square
        length: 3.5e-07
        kwargs:
          amp: 0.641247
          phase: -0.869926
          ramp_fraction: 0.25
      - channel: Q2.qdrv
        env: virtualz
        freq: single_qubit/2/GE/freq
        length: 0.0
        kwargs:
          phase: -1.94075
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: -0.023837
  (3, 4):
    CZ:
      freq: 5230000000.0
      pulse:
      - channel: Q3.qdrv
        env: cosine_square
        length: 2.5e-07
        kwargs:
          amp: 0.918229
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: cosine_square
        length: 2.5e-07
        kwargs:
          amp: 0.877766
          phase: -1.204779
          ramp_fraction: 0.25
      - channel: Q3.qdrv
        env: virtualz
        freq: single_qubit/3/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
  (4, 5):
    CZ:
      freq: 5400000000.0
      pulse:
      - channel: Q4.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.732658
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: cosine_square
        length: 2.0e-07
        kwargs:
          amp: 0.732658
          phase: 0.298501
          ramp_fraction: 0.25
      - channel: Q4.qdrv
        env: virtualz
        freq: single_qubit/4/GE/freq
        length: 0.0
        kwargs:
          phase: -0.441041
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.752092
  (5, 6):
    CZ:
      freq: 5500000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q5.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q5.qdrv
        env: virtualz
        freq: single_qubit/5/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (6, 7):
    CZ:
      freq: 5520000000.0
      pulse:
      - single_qubit/6/EF/X/pulse
      - channel: Q6.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.288
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q6.qdrv
        env: virtualz
        freq: single_qubit/6/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: 0.0
      - single_qubit/6/EF/X/pulse
  (7, 0):
    CZ:
      freq: 5370000000.0
      pulse:
      - channel: Q7.qdrv
        env: cosine_square
        length: 4.5e-07
        kwargs:
          amp: 0.795632
          phase: 0.0
          ramp_fraction: 0.25
      - channel: Q0.qdrv
        env: cosine_square
        length: 4.0e-07
        kwargs:
          amp: 0.706434
          phase: 0.692496
          ramp_fraction: 0.25
      - channel: Q7.qdrv
        env: virtualz
        freq: single_qubit/7/GE/freq
        length: 0.0
        kwargs:
          phase: -0.539758
      - channel: Q0.qdrv
        env: virtualz
        freq: single_qubit/0/GE/freq
        length: 0.0
        kwargs:
          phase: 0.026155
readout:
  0:
    channel: 7
    amp: 0.05
    freq: 6555456854.218374
    phase: 0.0
    delay: 4.0e-07
  1:
    channel: 4
    amp: 0.04
    freq: 6559107827.371197
    phase: 0.6
    delay: 4.0e-07
  2:
    channel: 1
    amp: 0.05
    freq: 6658504601.204804
    phase: -2.3
    delay: 4.0e-07
  3:
    channel: 3
    amp: 0.05
    freq: 6699523073.864432
    phase: 1.2
    delay: 4.0e-07
  4:
    channel: 5
    amp: 0.06
    freq: 6710258215.418671
    phase: -0.3
    delay: 4.0e-07
  5:
    channel: 6
    amp: 0.06
    freq: 6707928573.902684
    phase: -0.5
    delay: 4.0e-07
  6:
    channel: 2
    amp: 0.075
    freq: 6784291290.240388
    phase: 1.3
    delay: 4.0e-07
  7:
    channel: 0
    amp: 0.08
    freq: 6836587148.190145
    phase: 2.0
    delay: 4.0e-07
  esp:
    enable: false
    qubits:
    - 0
    - 2
    - 3
    - 5
    - 6
  herald: true
  length: 7.5e-07
  reset: 1.0e-05
  sample_rate: 500000000.0
  env: sine
  kwargs:
    phase: 0.0
reset:
  active:
    enable: false
    n_resets: 3
    feedback_delay: 2.0e-07
  passive:
    delay: 0.0005
hardware:
  ADC_sample_rate: null
  DAC_sample_rate: 8000000000.0
  readout_LO: null
  qubit_LO: null
