single_qubit:
  Q0:
    channel: Q0.qdrv
    GE:
      freq: 4461736318.073627
      X90:
        - env: 'DRAG'
          kwargs:
            alpha: 0.0 
            amp: 0.1
            anh: -270e6
            df: 0.0
            phase: 0.0
    EF:
      freq: 4181258902.85729
      X90:
        - env: 'cosine_square'
          kwargs:
            amp: 0.1
            phase: 0.0
            ramp_fraction: 0.25
  Q1:
    channel: Q1.qdrv
    GE:
      freq: 4675260858.059634
      X90:
        - env: 'DRAG'
          kwargs:
            alpha: 0.0 
            amp: 0.1
            anh: -270e6
            df: 0.0
            phase: 0.0
    EF:
      freq: 4400700000.0
      X90:
        - env: 'cosine_square'
          kwargs:
            amp: 0.1
            phase: 0.0
            ramp_fraction: 0.25
  Q2:
    channel: Q2.qdrv
    GE:
      freq: 4944461837.827577
      X90:
        - env: 'DRAG'
          kwargs:
            alpha: 0.0 
            amp: 0.1
            anh: -270e6
            df: 0.0
            phase: 0.0
    EF:
      freq: 4672600000.0
      X90:
        - env: 'cosine_square'
          kwargs:
            amp: 0.1
            phase: 0.0
            ramp_fraction: 0.25
  Q3:
    channel: Q3.qdrv
    GE:
      freq: 5114911040.024481
      X90:
        - env: 'DRAG'
          kwargs:
            alpha: 0.0 
            amp: 0.1
            anh: -270e6
            df: 0.0
            phase: 0.0
    EF:
      freq: 4849300000.0
      X90:
        - env: 'cosine_square'
          kwargs:
            amp: 0.1
            phase: 0.0
            ramp_fraction: 0.25
  Q4:
    channel: Q4.qdrv
    GE:
      freq: 5350927547.979777
      X90:
        - env: 'DRAG'
          kwargs:
            alpha: 0.0 
            amp: 0.1
            anh: -270e6
            df: 0.0
            phase: 0.0
    EF:
      freq: 5089500000.0
      X90:
        - env: 'cosine_square'
          kwargs:
            amp: 0.1
            phase: 0.0
            ramp_fraction: 0.25
  Q5:
    channel: Q5.qdrv
    GE:
      freq: 5581471962.572675
      X90:
        - env: 'DRAG'
          kwargs:
            alpha: 0.0 
            amp: 0.1
            anh: -270e6
            df: 0.0
            phase: 0.0
    EF:
      freq: 5263900000.0
      X90:
        - env: 'cosine_square'
          kwargs:
            amp: 0.1
            phase: 0.0
            ramp_fraction: 0.25
  Q6:
    channel: Q6.qdrv
    GE:
      freq: 5880552778.000434
      X90:
        - env: 'DRAG'
          kwargs:
            alpha: 0.0 
            amp: 0.1
            anh: -270e6
            df: 0.0
            phase: 0.0
    EF:
      freq: 5615900000.0
      X90:
        - env: 'cosine_square'
          kwargs:
            amp: 0.1
            phase: 0.0
            ramp_fraction: 0.25
  Q7:
    channel: Q7.qdrv
    GE:
      freq: 5621010772.789028
      X90:
        - env: 'DRAG'
          kwargs:
            alpha: 0.0 
            amp: 0.1
            anh: -270e6
            df: 0.0
            phase: 0.0
    EF:
      freq: 5356000000.0
      X90:
        - env: 'cosine_square'
          kwargs:
            amp: 0.1
            phase: 0.0
            ramp_fraction: 0.25
  common:
    length:
      X90: 2.4e-8
      X180: 4.8e-8
two_qubit:
  (0,1):
    amp: 0.288
    env: cos_square_DRAGdouble
    length: 2.0e-07
    freq: -391492904
    gate:
      CZ:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
        - [0, 0, 0, -1]
  (1,2):
    amp: 0.276
    env: cos_square_DRAGdouble
    length: 2.0e-07
    freq: -550458006.6
    gate:
      CZ:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
        - [0, 0, 0, -1]
  (2,3):
    amp: 0.518
    env: cos_square_DRAGdouble
    length: 2.5e-07
    freq: -580061901.137005
    gate:
      CZ:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
        - [0, 0, 0, -1]
  (3,4):
    amp: 0.546
    env: cos_square_DRAGdouble
    length: 4.0e-07
    freq: -350000000.0
    gate:
      CZ:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
        - [0, 0, 0, -1]
  (4,5):
    amp: 0.2369
    env: cos_square_DRAGdouble
    length: 2e-07
    freq: -255000000.0
    gate:
      CZ:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
        - [0, 0, 0, -1]
  (5,6):
    amp: 0.433
    env: cos_square_DRAGdouble
    length: 2.15e-07
    freq: -156000000.0
    gate:
      CZ:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
        - [0, 0, 0, -1]
  (6,7):
    amp: 0.28
    env: cos_square_DRAGdouble
    length: 2.5e-07
    freq: -151000000.0
    gate:
      CZ:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
        - [0, 0, 0, -1]
  (7,0):
    amp: 0.523
    env: cos_square_DRAGdouble
    length: 2.0e-07
    freq: -381000000.0
    gate:
      CZ:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
        - [0, 0, 0, -1]
readout:
  0:
    amp: 0.019724226371142798
    freq: 6554368952.374638
  1:
    amp: 0.01829905189877411
    freq: 6558439922.632911
  2:
    amp: 0.016645073053349783
    freq: 6658008967.32158
  3:
    amp: 0.017906057102356918
    freq: 6700134795.120309
  4:
    amp: 0.016127662739686993
    freq: 6711440184.690463
  5:
    amp: 0.0183
    freq: 6708160370.806432
  6:
    amp: 0.0305
    freq: 6785153568.914835
  7:
    amp: 0.93
    freq: 6835470849.262068
  env: cos_edge_square
  delay: 0.0
  ramp_fraction: 0.25
  length: 1.0e-6
  sample_rate: 8e9
reset:
  delay: 5e-4
hardware:
  sample_rate: 8e9
  clock_rate: 5e8
